# Generated by Django 3.2.7 on 2021-10-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_favourite_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='NimOfLikes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
