# Generated by Django 3.2.7 on 2021-10-31 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_rename_nimoflikes_anime_numoflikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('jonra', models.CharField(default='', max_length=100)),
                ('poster', models.TextField()),
                ('playlist', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anime.an'),
        ),
        migrations.DeleteModel(
            name='anime',
        ),
    ]
