# Generated by Django 3.2.7 on 2021-11-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='an',
            name='viewsNum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
