# Generated by Django 4.0 on 2022-02-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_remove_an_playlist_an_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='an',
            name='type',
        ),
    ]
