# Generated by Django 4.0 on 2022-02-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_remove_an_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='an',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
